providers = ["node"]

[phases.setup]
nixPkgs = [
    "nodejs",
    "chromium",
    "glib",
    "nss",
    "freetype",
    "harfbuzz",
    "cairo",
    "pango",
    "alsa-lib",
    "atk",
    "cups"
]